### ISSUE TITLE
( org.texttechnologylab.duui.ReproducibleAnnotation )  &&  ( Plugin 'maven-assembly-plugin:' not found )

### ISSUE THREAD

**Issue by p2keshtidar** [texttechnologylab/DockerUnifiedUIMAInterface#62]
***
org.texttechnologylab.duui.ReproducibleAnnotation fehlt.
die verwendung in:
1) org.texttechnologylab.DockerUnifiedUIMAInterface.driver.DUUIMADriver
2) org.texttechnologylab.DockerUnifiedUIMAInterface.driver.IDUUIInstantiatedPipelineComponent
3) org.texttechnologylab.DockerUnifiedUIMAInterface.tools.BorlandExport
4) org.texttechnologylab.DockerUnifiedUIMAInterface.tools.RemoveAnnotations
5) org.texttechnologylab.DockerUnifiedUIMAInterface.tools.SimpleSegmenter
6) org.texttechnologylab.DockerUnifiedUIMAInterface.DUUIPipelineAnnotationComponent
7) org.texttechnologylab.DockerUnifiedUIMAInterface.DUUIPipelineDescription
***

&&

***
pom.xml zeile 52  : Plugin 'maven-assembly-plugin:' not found

meine Loesung : add pluginManagement.
Code :
<build>
        <resources>
            <resource>
                <filtering>false</filtering>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>desc/type/**/*</exclude>
                    <exclude>org/**/*</exclude>
                </excludes>
            </resource>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
                <includes>
                    <include>desc/type/**/*</include>
                    <include>org/**/*</include>
                </includes>
            </resource>
        </resources>
        <pluginManagement>
            <plugins>

                <plugin>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <configuration>
                        <archive>
                            <manifest>
                                <mainClass>org.texttechnologylab.DockerUnifiedUIMAInterface.DUUIComposer</mainClass>
                            </manifest>
                        </archive>
                        <descriptorRefs>
                            <descriptorRef>jar-with-dependencies</descriptorRef>
                        </descriptorRefs>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>io.github.git-commit-id</groupId>
                    <artifactId>git-commit-id-maven-plugin</artifactId>
                    <version>5.0.0</version>
                    <executions>
                        <execution>
                            <id>get-the-git-infos</id>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                            <phase>initialize</phase>
                        </execution>
                    </executions>
                    <configuration>
                        <generateGitPropertiesFile>true</generateGitPropertiesFile>
                        <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
                        </generateGitPropertiesFilename>
                        <includeOnlyProperties>
                            <includeOnlyProperty>^git.build.(time|version)$</includeOnlyProperty>
                            <includeOnlyProperty>^git.commit.id.(abbrev|full)$</includeOnlyProperty>
                        </includeOnlyProperties>
                        <commitIdGenerationMode>full</commitIdGenerationMode>
                    </configuration>
                </plugin>
                <plugin>
                    
                    <groupId>org.apache.uima</groupId>
                    <artifactId>jcasgen-maven-plugin</artifactId>
                    <version>2.9.0</version>
                    <configuration>
                        <limitToProject>true</limitToProject>
                        <typeSystemIncludes>
                            <include>src/main/resources/org/texttechnologylab/types/reproducibleAnnotations.xml
                            </include>
                        </typeSystemIncludes>
                    </configuration>
                    <executions>
                        <execution>
                            
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>1.10</version>
                    <executions>
                        <execution>
                            <id>addToSourceFolder</id>
                            <goals>
                                
                                <goal>add-source</goal>
                            </goals>
                            <phase>process-sources</phase>
                            <configuration>
                                <sources>
                                    
                                    <source>${project.build.directory}/generated-sources/jcasgen</source>
                                </sources>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                    <configuration>
                        <source>11</source>
                        <target>11</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.22.0</version>
                    <configuration>
                        <argLine>
                            --illegal-access=permit
                        </argLine>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>2.22.0</version>
                    <configuration>
                        <argLine>
                            --illegal-access=permit
                        </argLine>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

**Comment by p2keshtidar** [comment]
there was a build error. but found another Error.
***
Dec 28, 2023 6:20:58 AM com.github.dockerjava.core.DockerClientBuilder build
WARNING: 'dockerHttpClient' should be set.Falling back to Jersey, will be an error in future releases.
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported protocol scheme: npipe:////./pipe/docker_engine
	at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.<init>(JerseyDockerHttpClient.java:225)
	at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.<init>(JerseyDockerHttpClient.java:49)
	at com.github.dockerjava.jaxrs.JerseyDockerHttpClient$Builder.build(JerseyDockerHttpClient.java:124)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:106)
	at org.texttechnologylab.DockerUnifiedUIMAInterface.DUUIDockerInterface.<init>(DUUIDockerInterface.java:167)
	at org.texttechnologylab.DockerUnifiedUIMAInterface.driver.DUUISwarmDriver.<init>(DUUISwarmDriver.java:42)
	at org.texttechnologylab.DockerUnifiedUIMAInterface.DUUIComposer.main(DUUIComposer.java:1167)
***
unfortunately could not find solution.
the Problem Line is :  _docker = DockerClientBuilder.getInstance().build();

**Comment by abrami** [comment]
Solution regarding the reproducible annotations, as specified in the description:

mvn clean compile exec:java -Dexec.mainClass="org.texttechnologylab.DockerUnifiedUIMAInterface.DUUIComposer"

**Comment by abrami** [comment]
solved, closed.
